import { type Collection } from "@/lib/collections";

export const createDemoData = (): Collection[] => [
  {
    id: "demo-1",
    title: "Marketing Content",
    description: "TikTok marketing videos and strategies",
    userId: "demo-user",
    videos: [
      {
        id: "1",
        url: "https://www.tiktok.com/@adamstewartmarketing/video/7517620965812079879",
        platform: "tiktok" as const,
        title: "Adam Stewart Marketing Strategy",
        description: "Marketing insights and strategies",
        thumbnailUrl:
          "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068/oUGAAfEIQeIBDKzBfJAGCgAEIzBzBJJJfI~tplv-dmt-logom:tos-maliva-p-0000/4d8a2b0e8f4c4d2b8f4c4d2b8f4c4d2b",
        author: "@adamstewartmarketing",
        duration: 30,
        createdAt: new Date("2024-01-15"),
        metadata: {
          likes: 1250,
          comments: 89,
          shares: 156,
          views: 12500,
        },
      },
      {
        id: "2",
        url: "https://www.tiktok.com/@example/video/1234567890",
        platform: "tiktok" as const,
        title: "Content Creation Tips",
        description: "How to create engaging content",
        thumbnailUrl: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=400&fit=crop",
        author: "@contentcreator",
        duration: 45,
        createdAt: new Date("2024-01-14"),
        metadata: {
          likes: 890,
          comments: 45,
          shares: 78,
          views: 8900,
        },
      },
      {
        id: "3",
        url: "https://www.instagram.com/reel/example123/",
        platform: "instagram" as const,
        title: "Instagram Growth Hack",
        description: "Quick tips for Instagram growth",
        thumbnailUrl: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=400&fit=crop",
        author: "@instagramguru",
        duration: 60,
        createdAt: new Date("2024-01-13"),
        metadata: {
          likes: 2100,
          comments: 167,
          shares: 234,
          views: 15600,
        },
      },
      {
        id: "4",
        url: "https://www.tiktok.com/@business/video/9876543210",
        platform: "tiktok" as const,
        title: "Business Strategy 101",
        description: "Essential business strategies for entrepreneurs",
        thumbnailUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
        author: "@businessexpert",
        duration: 90,
        createdAt: new Date("2024-01-12"),
        metadata: {
          likes: 3400,
          comments: 289,
          shares: 456,
          views: 28900,
        },
      },
      {
        id: "5",
        url: "https://www.instagram.com/reel/example456/",
        platform: "instagram" as const,
        title: "Social Media Trends 2024",
        description: "Latest trends in social media marketing",
        thumbnailUrl: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&h=400&fit=crop",
        author: "@trendwatcher",
        duration: 75,
        createdAt: new Date("2024-01-11"),
        metadata: {
          likes: 1890,
          comments: 134,
          shares: 298,
          views: 19800,
        },
      },
      {
        id: "6",
        url: "https://www.tiktok.com/@creative/video/5555555555",
        platform: "tiktok" as const,
        title: "Creative Process Behind Viral Content",
        description: "How to create content that goes viral",
        thumbnailUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&h=400&fit=crop",
        author: "@creativemind",
        duration: 120,
        createdAt: new Date("2024-01-10"),
        metadata: {
          likes: 5600,
          comments: 445,
          shares: 789,
          views: 45600,
        },
      },
    ],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "demo-2",
    title: "Educational Content",
    description: "Learning and tutorial videos",
    userId: "demo-user",
    videos: [
      {
        id: "7",
        url: "https://www.tiktok.com/@educator/video/7777777777",
        platform: "tiktok" as const,
        title: "Quick Learning Tips",
        description: "How to learn faster and retain more",
        thumbnailUrl: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400&h=400&fit=crop",
        author: "@educator",
        duration: 45,
        createdAt: new Date("2024-01-09"),
        metadata: {
          likes: 2300,
          comments: 178,
          shares: 345,
          views: 23400,
        },
      },
      {
        id: "8",
        url: "https://www.instagram.com/reel/education789/",
        platform: "instagram" as const,
        title: "Study Techniques That Work",
        description: "Proven study methods for better results",
        thumbnailUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=400&fit=crop",
        author: "@studyexpert",
        duration: 90,
        createdAt: new Date("2024-01-08"),
        metadata: {
          likes: 1670,
          comments: 89,
          shares: 167,
          views: 16700,
        },
      },
    ],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-09"),
  },
];
